### PR TITLE
to support additional stellar messages and message types

### PR DESCRIPTION
**Pull request by b-yap**

### CODE REVIEW

**Review by ebma — APPROVED** [review]
LGTM, but having more context on what exactly you did here would be nice. I assume you re-generated the XDR things, but changed more than that manually (?)

**Comment by b-yap** [comment]
@ebma  Okay, so I got stuck last Friday and partially today, on mapping the  slot id, given the `tx_set_hash` from the `scpmessage`, 
and the transactionset which we get from `TxSet(...)`. 

I followed the hashing function from Stellar Core:
https://github.com/stellar/stellar-core/blob/master/src/herder/TxSetFrame.cpp#L180-L190
and temporarily placed it in a helper file https://github.com/pendulum-chain/stellar-experiments/blob/85-collect-and-store-scp-messages-in-vault-client/src/helper.rs#L33-L43

And this function is also called from another function, only if the message type is `isGeneralizedTxSet`... which is something that we don't have.
https://github.com/stellar/stellar-core/blob/master/src/herder/TxSetFrame.cpp#L825-L829

It's more of a "just in case".

**Comment by ebma** [comment]
But it says in most comments, that it was auto-generated. Is it?

**Comment by b-yap** [comment]
yes. i had to run the npm install and npm build in the autogenerator directory. That's how the type.rs is updated.

**Review by TorstenStueber — APPROVED** [review]
If `types.rs` has been auto-generated with the [autogenerator in this repo](https://github.com/pendulum-chain/substrate-stellar-sdk/tree/master/autogenerator), then this is fine. I did not expect that so many types would change. That usually means that some of the manually written code in this repo also needs to be touched, but that was not the case here (?) @b-yap? Did the crate with the new auto generated code still build with errors (using cargo)?

**Comment by b-yap** [comment]
@TorstenStueber  the code compiled with no problems, even with the updated types.rs.

update: ah, the test did not, however. You are correct, it needs to be updated.

**Comment by TorstenStueber** [comment]
The tests are fixed now.

**Pull request merged**
